### ISSUE TITLE
support for force_ssl from config file

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice-docs#3]
Support for force ssl from the configuration file will be great from the configuration file well presently this can be achieved by making an entry in htaccess.

**Comment by mschering** [comment]
In my opinion this is not something Group-Office should do. The webserver must take care of it.

**Comment by s1-ranjan** [comment]
Imposing ssl from Group-Office configuration file can remove the dependency of the web server behaviour.

**Comment by mschering** [comment]
Sorry, I really think the webserver is the place to put the redirect.
