### ISSUE TITLE
Missing documentation for CLI and System API

### ISSUE THREAD

**Issue by Skywrath-Mage** [Intermesh/groupoffice-docs#4]
Hello,
the documentation for the api systems is missing and the CLI does not have the list of available commands.
Can you add it please?

**Comment by jvoix** [comment]
These are the commands we typically use:

1. Run sync filesystem:  sudo -u www-data php /usr/share/groupoffice/groupofficecli.php -r=files/folder/syncFilesystem >/tmp/GOfilesync.txt
2. Run check database : sudo -u www-data php /usr/share/groupoffice/groupofficecli.php -r=maintenance/checkDatabase>/tmp/GOcheck.txt
3. Run build search cache:  sudo -u www-data php /usr/share/groupoffice/groupofficecli.php -r=maintenance/buildSearchCache>/tmp/GOsearchindex.txt

**Comment by mschering** [comment]
Thanks.  I've documented this now under System Settings -> Tools.
